apiVersion: batch/v1
kind: CronJob
metadata:
  name: pastely-delete-expired-paste
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            args:
            - "-X"
            - "DELETE"
            - "http://service-pastely.default.svc.cluster.local:8080/api/v1/paste"
          restartPolicy: OnFailure