apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-pastely
data:
  APP_NAME: "pastly"
  APP_PORT: "8080"
  APP_ENV: "production"
  DB_MASTER_DSN: "postgresql://pastely:4clZyD5q8HEsOLtyWyCCc4pCHDTFWsS4ZMYClmcL18DMUfM84es0nA2WmsWUbd1W@postgres-pastely-production-pooler.default.svc.cluster.local:5432/pastely?sslmode=require"
  DB_SLAVE_DSN: "postgresql://pastely:4clZyD5q8HEsOLtyWyCCc4pCHDTFWsS4ZMYClmcL18DMUfM84es0nA2WmsWUbd1W@postgres-pastely-production-pooler-repl.default.svc.cluster.local:5432/pastely?sslmode=require"
  DB_ANALYTIC_DSN: "postgresql://pastely:CbEgyqpUTRt5S6MqkDamgcbT2NXe4oA1RwmXFK90FbxJsQdfoTkIo60foZjzdf8Z@postgres-timescale-pastely-productioon-pooler.default.svc.cluster.local:5432/pastely?sslmode=require"
  APP_FILE_STORAGE: "minio"
  S3_BUCKET_NAME: "pastely-bucket"
  S3_BUCKET_REGION: "us-east-1"
  S3_BUCKET_ENDPOINT: "http://minio-service.default.svc.cluster.local:9000"
  S3_BUCKET_ACCESS_KEY: "ppZwtlQOz51ZInKKMBS5"
  S3_BUCKET_SECRET_KEY: "D7FkmoJAEi9BokZK4uQFfeAoLn8H4ZXV9LFxm906"
  PROMETHEUS_MONITORING_ENABLED: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastely
spec:
  selector:
    matchLabels:
      app: pastely
  template:
    metadata:
      labels:
        app: pastely
    spec:
      hostNetwork: true
      dnsConfig:
        nameservers:
        - 10.96.0.10
        searches:
        - default.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      dnsPolicy: None
      containers:
      - name: pastely
        image: kadekchresna/pastely
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: pastely-port
        envFrom:
        - configMapRef:
            name: config-map-pastely

---

apiVersion: v1
kind: Service
metadata:
  name: service-pastely
spec:
  selector:
    app: pastely
  ports:
  - port: 8080
    targetPort: 8080
    name: pastely-port
    protocol: TCP
    nodePort: 31080
  type: NodePort
