apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-pastely
data:
  APP_NAME: "pastly"
  APP_PORT: "8080"
  APP_ENV: "production"
  DB_MASTER_DSN: "postgresql://postgres:admin@host.minikube.internal:5432/postgres?sslmode=disable"
  DB_SLAVE_DSN: "postgresql://postgres:admin@host.minikube.internal:5432/postgres?sslmode=disable"
  DB_ANALYTIC_DSN: "postgresql://postgres:admin@host.minikube.internal:6543/postgres?sslmode=disable"
  APP_FILE_STORAGE: "minio"
  S3_BUCKET_NAME: "pastely-bucket"
  S3_BUCKET_REGION: "us-east-1"
  S3_BUCKET_ENDPOINT: "http://host.minikube.internal:9000"
  S3_BUCKET_ACCESS_KEY: "ppZwtlQOz51ZInKKMBS5"
  S3_BUCKET_SECRET_KEY: "vjwk9od4U6HQzRcymNo2lNwbFYC0j1KhBzDDyMgb"
  PROMETHEUS_MONITORING_ENABLED: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastely
spec:
  selector:
    matchLabels:
      app: pastely
  template:
    metadata:
      labels:
        app: pastely
    spec:
      hostNetwork: true
      dnsConfig:
        nameservers:
        - 10.96.0.10
        searches:
        - default.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      dnsPolicy: None
      containers:
      - name: pastely
        image: kadekchresna/pastely
        resources:
          requests:
            cpu: "200m"   # 200 millicores
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "250Mi"
        ports:
        - containerPort: 8080
          name: pastely-port
        envFrom:
        - configMapRef:
            name: config-map-pastely

---

apiVersion: v1
kind: Service
metadata:
  name: service-pastely
spec:
  selector:
    app: pastely
  ports:
  - port: 8080
    targetPort: 8080
    name: pastely-port
    protocol: TCP
    nodePort: 31080
  type: NodePort


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pastelly-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pastely
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
