

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  storageClassName: minio-storage-class
  accessModes:
    - ReadWriteOnce

---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
# 
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio-pastely # Change this value to match the namespace metadata.name
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9090
    volumeMounts:
    - mountPath: /data
      name: minio-pvc # Corresponds to the `spec.volumes` Persistent Volume Claim
  volumes:
  - name: minio-pvc
    hostPath: # MinIO generally recommends using locally-attached volumes
      path: /mnt/minio/data # Specify a path to a local drive or volume on the Kubernetes worker node
      type: DirectoryOrCreate # The path to the last directory must exist

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
  - name: minio-port-server
    port: 9090
    targetPort: 9090
    nodePort: 39090
    type: NodePort
  - name: minio-port-console
    port: 9091
    targetPort: 9091
    nodePort: 39091
    type: NodePort
