apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: postgres-pastely-production
  namespace: default
spec:
  allowedSourceRanges: []
  numberOfInstances: 3
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  enableConnectionPooler: true
  enableReplicaConnectionPooler: true
  enableMasterPoolerLoadBalancer: true
  enableReplicaPoolerLoadBalancer: true
  maintenanceWindows: []
  volume:
    size: 1Gi
    throughput: 125
    iops: 3000
    storageClass: standard
  postgresql:
    version: '16'
  users:
    pastely: []
  databases:
    pastely: pastely
  resources:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 100Mi