apiVersion: v1
kind: Secret
metadata:
  name: pastely-timescale-secret
type: Opaque
data:
  password: cGFzc3dvcmQxMjM= 

--- 

apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: postgres-timescale-pastely-productioon
  namespace: default
spec:
  teamId: acid
  allowedSourceRanges: []
  numberOfInstances: 1
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: false
  enableConnectionPooler: true
  enableReplicaConnectionPooler: false
  enableMasterPoolerLoadBalancer: true
  enableReplicaPoolerLoadBalancer: false
  maintenanceWindows: []
  volume:
    size: 1Gi
    throughput: 125
    iops: 3000
    storageClass: standard
  postgresql:
    version: '16'
  users:
    pastely: []
  databases:
    pastely: pastely
  preparedDatabases:
    pastely:
      extensions:
        timescaledb: public
  resources:
    limits:
      cpu: 250m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 100Mi
  secret:
    pastely: pastely-timescale-secret
