apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-pastely-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---


# minikube ssh
# sudo mkdir -p /var/postgres/data
# sudo chmod 777 -R /var/postgres

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pastely-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: postgres-pastely-storage-class
  hostPath:
    path: /var/postgres/postgres-pastely-pv-1/pgdata
    type: DirectoryOrCreate


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pastely-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: postgres-pastely-storage-class
  hostPath:
    path: /var/postgres/postgres-pastely-pv-2/pgdata
    type: DirectoryOrCreate


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pastely-pv-0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: postgres-pastely-storage-class
  hostPath:
    path: /var/postgres/postgres-pastely-pv-0/pgdata
    type: DirectoryOrCreate

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loganal-pastely-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-timescale-pastely-pv-0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: loganal-pastely-storage-class
  hostPath:
    path: /var/postgres/postgres-timescale-pastely-pv-0/pgdata
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-timescale-pastely-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: loganal-pastely-storage-class
  hostPath:
    path: /var/postgres/postgres-timescale-pastely-pv-1/pgdata
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-timescale-pastely-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: loganal-pastely-storage-class
  hostPath:
    path: /var/postgres/postgres-timescale-pastely-pv-2/pgdata
    type: DirectoryOrCreate
