
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pastely-pv-0
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-storage-class
  hostPath:
    path: /var/minio/data
    type: DirectoryOrCreate